### ISSUE TITLE
publish to npm and add travis

### ISSUE THREAD

**Issue by queckezz** [micro-js/to-inline-style#1]
I don't have permissions to publish to npm. Can you maybe finalize the repo @ashaffer? Add the repo to travis & publish to npm.

**Comment by ashaffer** [comment]
Looks pretty good. I'll email you the npm login so you can publish things.

However, a few nitpicks. Peformance is pretty critical for something like this that would be running inside lots of components during the render. I did some benchmarking, and I think it can be somewhat significantly faster:

http://jsperf.com/to-inline-style

I created an unreasonable number of test cases for different things. The fastest is pretty clearly the for-in variants (though this would not be the case if the objects were in dictionary mode, e.g. if they had had a key deleted from them) without hasOwnProperty checking. for-in with no hasOwnProperty gets us like 30% more speed, but at the cost of doing weird stuff if things are on the prototype. Might not be worthwhile. Could break things if people were passing around special style/theme class-like things or something -  though that would be a kinda weird thing to do.

The code generation one is the next fastest, though it's a pretty weird implementation, and might not be worth the relatively small gain it offers.

Of note, in addition to modifying the toStyle functions I also modified `hyphenate` to do its job in a single pass.

Also, super minor nitpick, in the tests you don't need to `require('../lib')` you can just `require('..')`.

**Comment by queckezz** [comment]
Great! Excited to contribute back.

I haven't looked at performance at all. But you're definitely right, this is a very performance critical module. And wow native map is slow. I'll apply your changes when I get home. Will also try out `@f/map-array` for comparison too.

> I created an unreasonable number of test cases for different things. 

Yea pretty impressive with what you've come up with :p 

> the fastest is pretty clearly the for-in variants

I'm assuming you did the benchmarks on chrome right? Running them on IE gives quite some different results and the crazy mode is actually the fastest. But still, I think the for-in is probably the optimum.

![04-01-_2016_09-34-06](https://cloud.githubusercontent.com/assets/2580598/12086036/667bf0ae-b2c6-11e5-8e70-18e5b20690a7.png)

> Also, super minor nitpick, in the tests you don't need to  require('../lib')  you can just  require('..') 

I actually changed that from the khaos template, didn't knew that works!
